#!/bin/bash

set -o errexit

set -o nounset


worker_ready(){
    celery -A ecommerce inspect ping
}

until worker_ready; do 
    >&2 echo 'Celery workers not available. waiting...'
    sleep 1

done
>&2 echo 'Celery workers are available and ready.'

flower \
    --app=real_estate \
    --broker="amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@broker:5672/vhost"